### ISSUE TITLE
Generate Vagrant/VirtualBox automated OpenStack Environment with Puppet

### ISSUE THREAD

**Issue by erick0z** [includeproject/GPUaaS#3]
## Openstack 3 nodes Infrastructure

-4 VMs in VirtualBox:
    \* 1 Puppet Master with Openstack modules(Juno)
    \* 3 Puppet agents(1 can be cloned 2 times)<br>
-Vagrant file for automatic deployment
-Extra scripts

**Comment by VictorRodriguez** [comment]
I think this will require @obedmr  review
